In [1]:
import pandas as pd
from pathlib import Path

In [2]:
csvpath = Path("../Resources/Texas_Pricing_Data.csv")

In [3]:
pricing_data_df = pd.read_csv(csvpath)

In [4]:
pricing_data_df.head()

,month_date_yyyymm,postal_code,zip_name,median_listing_price,active_listing_count,median_days_on_market,new_listing_count,price_increased_count,price_reduced_count,pending_listing_count,median_listing_price_per_square_feet,median_square_feet,average_listing_price,total_listing_count,pending_ratio
0,202006,77414,"bay city, tx",202549.5,130,105.5,40,0,16,31,113.793981,1700.0,232176,161,0.2385
1,202006,77087,"houston, tx",205050.0,21,80.5,4,0,4,19,124.456393,1615.0,227396,40,0.9048
2,202006,77024,"houston, tx",1249550.0,396,73.5,108,0,92,77,302.330691,3815.0,1759357,473,0.1944
3,202006,77020,"houston, tx",292500.0,66,72.5,28,4,16,32,167.322558,1666.0,273267,98,0.4848
4,202006,77983,"seadrift, tx",255050.0,22,136.5,0,0,4,9,153.846154,1746.0,288390,31,0.4091

In [5]:
pricing_data_df.set_index(pd.to_datetime(pricing_data_df['month_date_yyyymm'], format='%Y%m', infer_datetime_format=True), inplace=True)
pricing_data_df.head()

,month_date_yyyymm,postal_code,zip_name,median_listing_price,active_listing_count,median_days_on_market,new_listing_count,price_increased_count,price_reduced_count,pending_listing_count,median_listing_price_per_square_feet,median_square_feet,average_listing_price,total_listing_count,pending_ratio
month_date_yyyymm,,,,,,,,,,,,,,,
2020-06-01,202006,77414,"bay city, tx",202549.5,130,105.5,40,0,16,31,113.793981,1700.0,232176,161,0.2385
2020-06-01,202006,77087,"houston, tx",205050.0,21,80.5,4,0,4,19,124.456393,1615.0,227396,40,0.9048
2020-06-01,202006,77024,"houston, tx",1249550.0,396,73.5,108,0,92,77,302.330691,3815.0,1759357,473,0.1944
2020-06-01,202006,77020,"houston, tx",292500.0,66,72.5,28,4,16,32,167.322558,1666.0,273267,98,0.4848
2020-06-01,202006,77983,"seadrift, tx",255050.0,22,136.5,0,0,4,9,153.846154,1746.0,288390,31,0.4091

In [7]:
pricing_data_df.drop('month_date_yyyymm',axis=1,inplace=True)
pricing_data_df.head()

,postal_code,zip_name,median_listing_price,active_listing_count,median_days_on_market,new_listing_count,price_increased_count,price_reduced_count,pending_listing_count,median_listing_price_per_square_feet,median_square_feet,average_listing_price,total_listing_count,pending_ratio
month_date_yyyymm,,,,,,,,,,,,,,
2020-06-01,77414,"bay city, tx",202549.5,130,105.5,40,0,16,31,113.793981,1700.0,232176,161,0.2385
2020-06-01,77087,"houston, tx",205050.0,21,80.5,4,0,4,19,124.456393,1615.0,227396,40,0.9048
2020-06-01,77024,"houston, tx",1249550.0,396,73.5,108,0,92,77,302.330691,3815.0,1759357,473,0.1944
2020-06-01,77020,"houston, tx",292500.0,66,72.5,28,4,16,32,167.322558,1666.0,273267,98,0.4848
2020-06-01,77983,"seadrift, tx",255050.0,22,136.5,0,0,4,9,153.846154,1746.0,288390,31,0.4091

In [8]:
pricing_data_df.sort_values(by=['postal_code','month_date_yyyymm'], inplace=True)
pricing_data_df.head()

,postal_code,zip_name,median_listing_price,active_listing_count,median_days_on_market,new_listing_count,price_increased_count,price_reduced_count,pending_listing_count,median_listing_price_per_square_feet,median_square_feet,average_listing_price,total_listing_count,pending_ratio
month_date_yyyymm,,,,,,,,,,,,,,
2016-07-01,77002,"houston, tx",312050.0,52,88.0,12,0,8,15,253.271422,1266.0,499723,67,0.2885
2016-08-01,77002,"houston, tx",349050.0,54,89.5,12,0,12,20,250.615461,1365.5,505122,74,0.3704
2016-09-01,77002,"houston, tx",339050.0,57,76.5,12,0,8,12,248.215391,1375.5,476139,69,0.2105
2016-10-01,77002,"houston, tx",326050.0,55,80.0,8,0,4,8,241.769547,1338.0,439559,63,0.1455
2016-11-01,77002,"houston, tx",329050.0,53,83.0,16,0,4,8,245.061046,1276.5,425851,61,0.1509

In [17]:
pricing_data_df['pct_price_change'] = pricing_data_df['median_listing_price'].pct_change()
pricing_data_df.head()

,postal_code,zip_name,median_listing_price,active_listing_count,median_days_on_market,new_listing_count,price_increased_count,price_reduced_count,pending_listing_count,median_listing_price_per_square_feet,median_square_feet,average_listing_price,total_listing_count,pending_ratio,pct_price_change
month_date_yyyymm,,,,,,,,,,,,,,,
2016-07-01,77002,"houston, tx",312050.0,52,88.0,12,0,8,15,253.271422,1266.0,499723,67,0.2885,NaN
2016-08-01,77002,"houston, tx",349050.0,54,89.5,12,0,12,20,250.615461,1365.5,505122,74,0.3704,0.118571
2016-09-01,77002,"houston, tx",339050.0,57,76.5,12,0,8,12,248.215391,1375.5,476139,69,0.2105,-0.028649
2016-10-01,77002,"houston, tx",326050.0,55,80.0,8,0,4,8,241.769547,1338.0,439559,63,0.1455,-0.038342
2016-11-01,77002,"houston, tx",329050.0,53,83.0,16,0,4,8,245.061046,1276.5,425851,61,0.1509,0.009201

In [ ]:
pricing_data_df['pct_price_change'] = pricing_data_df['median_listing_price'].pct_change()
pricing_data_df

In [19]:
pricing_data_df['pct_price_sqft_change'] = pricing_data_df['median_listing_price_per_square_feet'].pct_change()
pricing_data_df

,postal_code,zip_name,median_listing_price,active_listing_count,median_days_on_market,new_listing_count,price_increased_count,price_reduced_count,pending_listing_count,median_listing_price_per_square_feet,median_square_feet,average_listing_price,total_listing_count,pending_ratio,pct_price_change,pct_price_sqft,pct_price_sqft_change
month_date_yyyymm,,,,,,,,,,,,,,,,,
2016-07-01,77002,"houston, tx",312050.0,52,88.0,12,0,8,15,253.271422,1266.0,499723,67,0.2885,NaN,NaN,NaN
2016-08-01,77002,"houston, tx",349050.0,54,89.5,12,0,12,20,250.615461,1365.5,505122,74,0.3704,0.118571,-0.010487,-0.010487
2016-09-01,77002,"houston, tx",339050.0,57,76.5,12,0,8,12,248.215391,1375.5,476139,69,0.2105,-0.028649,-0.009577,-0.009577
2016-10-01,77002,"houston, tx",326050.0,55,80.0,8,0,4,8,241.769547,1338.0,439559,63,0.1455,-0.038342,-0.025969,-0.025969
2016-11-01,77002,"houston, tx",329050.0,53,83.0,16,0,4,8,245.061046,1276.5,425851,61,0.1509,0.009201,0.013614,0.013614
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-02-01,77995,"yoakum, tx",209850.0,29,133.0,8,0,4,9,100.147275,2103.0,342624,38,0.3103,0.049512,0.033128,0.033128
2020-03-01,77995,"yoakum, tx",202400.0,29,142.0,0,0,0,11,91.252346,2050.0,326075,40,0.3793,-0.035502,-0.088818,-0.088818
2020-04-01,77995,"yoakum, tx",194500.0,31,105.0,8,0,0,4,99.498926,1917.0,295784,35,0.1290,-0.039032,0.090371,0.090371
2020-05-01,77995,"yoakum, tx",198550.0,31,120.0,4,0,8,8,100.147275,2103.0,328709,39,0.2581,0.020823,0.006516,0.006516
2020-06-01,77995,"yoakum, tx",219550.0,27,99.5,4,0,0,12,98.611774,2103.5,359262,39,0.4444,0.105767,-0.015332,-0.015332